print('Hello world')
print('Hello Python!')
print('Hello QAForEveryone!')
print(' --------')
print('|       |')
print('|       |')
print('|       |')
print(' --------')
# or
print("-"*8)
print("|" + " "*7 + "|")
print("|" + " "*7 + "|")
print("|" + " "*7 + "|")
print("-"*8)